#! /bin/sh
set -xv
exec 2>>/tmp/bspwm.log

intern=eDP-1-1
extern=HDMI-0

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr | grep "$extern connected"; then
  bspc monitor $extern -d 1 2 3 4 5
  bspc monitor $intern -d 6 7 8 9 0
else
  bspc monitor $intern -d 1 2 3 4 5
fi

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color  "#f5bde6"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

if xrandr | grep "$extern connected"; then
  xrandr --output $intern --mode 1920x1080 --pos 3840x1080 --rotate normal --output DP-1 --off --output HDMI-1 --off --output $extern --primary --mode 3840x2160 --pos 0x0 --rotate normal --scale 0.80x0.80 --output DP-1-0 --off --output DP-1-1 --off
else
  xrandr --output $intern --primary --mode 1920x1080 --rotate normal
fi

feh --bg-scale ~/Pictures/arch-magenta-pink-1920x1080.png
~/.config/polybar/launch.sh
picom --experimental-backends --conf ~/.config/picom/picom.conf --xrender-sync-fence
