#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [[ $(xrandr -q | grep 'HDMI-2 connected') ]]
then
xrandr --output DP-1 --primary --rotate normal --mode 1366x768 --rate 60 --output HDMI-2 --rotate normal --mode 1366x768 --rate 60 --right-of DP-1
else
xrandr --output DP-1 --primary --rotate normal --mode 1366x768 --rate 60
fi
feh --bg-scale /home/adal/Downloads/debian-magenta-blue-1920x1080.png
picom --conf $HOME/.config/picom/picom.conf --experimental-backends